/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include<stdint.h>

int main(void)
{
    uint32_t *pClkCtrlReg      = (uint32_t*)0x4002104C;  // RCC_AHB2ENR 주소
    uint32_t *pPortCModeReg    = (uint32_t*)0x48000800;  // GPIOC_MODER 주소
    uint32_t *pPortCOutReg     = (uint32_t*)0x48000814;  // GPIOC_ODR 주소
    uint32_t *pPortAModeReg    = (uint32_t*)0x48000000;  // GPIOA_MODER 주소
    uint32_t *pPortAInReg      = (uint32_t*)0x48000010;  // GPIOA_IDR 주소
    uint32_t *pPortAPullUpDown = (uint32_t*)0x4800000C;  // GPIOA_PUPDR 주소

    // 1. GPIO 클럭 활성화
    *pClkCtrlReg |= (1 << 3);  // GPIOCEN 비트 설정
    *pClkCtrlReg |= (1 << 0);  // GPIOAEN 비트 설정

    // 2. GPIOC 핀 13을 출력 모드로 설정
    *pPortCModeReg &= ~(3 << 26);  // 26, 27 비트를 클리어
    *pPortCModeReg |= (1 << 26);   // 출력 모드로 설정

    // 3. GPIOA 핀 0을 입력 모드로 설정
    *pPortAModeReg &= ~(3 << 0);   // GPIOA 핀 0을 입력 모드로 설정

    // 4. GPIOA 핀 0 풀업 설정
    *pPortAPullUpDown &= ~(3 << 0); // 클리어
    *pPortAPullUpDown |= (1 << 0);  // 풀업 설정

    // 5. 무한 루프
    while (1)
    {
        uint8_t pinStatus = (uint8_t)(*pPortAInReg & 0x1); // GPIOA 핀 0 상태 읽기
        if (pinStatus)
        {
            *pPortCOutReg |= (1 << 13);  // GPIOC 핀 13 HIGH (LED ON)
        }
        else
        {
            *pPortCOutReg &= ~(1 << 13); // GPIOC 핀 13 LOW (LED OFF)
        }
    }
}

