/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*
//open OCD 디버거를 통해 세미호스팅
#include <stdio.h>

extern void initialise_monitor_handles(void);
int main(void)
{
	initialise_monitor_handles();
	printf("Hello world\n");

	for(;;);
}
*/
//SWV ITM Data Console
#include<stdio.h>
int main(void)
{
	printf("Size of char data type is %u\n", sizeof(char));
	printf("Size of short data type is %u\n", sizeof(short));
	printf("Size of int data type is %u\n", sizeof(int));
	printf("Size of long data type is %u\n", sizeof(long));
	printf("Size of long long data type is %u\n", sizeof(long long));
	printf("Size of double data type is %u\n", sizeof(double));
	for(;;);
}



