/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//sec18 강의에서는 GPIOD를 사용하지만 내 보드에선 GPIOC를 사용해야함
/*
#include<stdint.h>

int main(void)
{
    uint32_t *pClkCtrlReg   = (uint32_t*)0x4002104C;  // RCC_AHB2ENR 주소
    uint32_t *pPortCModeReg = (uint32_t*)0x48000800;  // GPIOC_MODER 주소
    uint32_t *pPortCOutReg  = (uint32_t*)0x48000814;  // GPIOC_ODR 주소

    // 1. GPIOC 주변 장치 클록 활성화
    *pClkCtrlReg |= 0x04; // GPIOCEN 비트 설정

    // 2. I/O 핀의 모드를 출력으로 설정 (PC13)
    *pPortCModeReg &= 0xF3FFFFFF; // 26, 27 비트를 클리어 (입력 모드로 설정)
    *pPortCModeReg |= 0x01000000; // 26번 비트를 1로 설정 (출력 모드)

    // 3. 출력 데이터 레지스터의 13번째 비트를 1로 설정하여 I/O 핀 13번을 HIGH 설정
    *pPortCOutReg |= 0x2000; // ODR13 비트 설정

    while(1); // 무한 루프
}
*/
//sec19 비트 시프트 연산자의 적용
#include<stdint.h>

int main(void)
{
    uint32_t *pClkCtrlReg   = (uint32_t*)0x4002104C;  // RCC_AHB2ENR 주소
    uint32_t *pPortCModeReg = (uint32_t*)0x48000800;  // GPIOC_MODER 주소
    uint32_t *pPortCOutReg  = (uint32_t*)0x48000814;  // GPIOC_ODR 주소

    // 1. GPIOC 주변 장치 클록 활성화(SET the 3rd bit position)
    *pClkCtrlReg |= (1 << 3); // GPIOCEN 비트 설정

    // 2. I/O 핀의 모드를 출력으로 설정 (PC13)
    *pPortCModeReg &= ~(3 << 26);  // 26, 27 비트를 클리어 (입력 모드로 설정)
    *pPortCModeReg |= (1 << 26);   // 26번 비트를 1로 설정 (출력 모드)
    // 3. 출력 데이터 레지스터의 13번째 비트를 1로 설정하여 I/O 핀 13번을 HIGH로 설정
    *pPortCOutReg |= (1 << 13);    // ODR13 비트 설정

    while(1); // 무한 루프
}
